const players = [
  {
    id: 1,
    name: "Luka Doncic",
    team: "LAL",
    position: "G",
    stats: { pts: 33.5, reb: 7.7, ast: 8.3, stl: 1.6, blk: 0.5, to: 4.0 },
  },
  {
    id: 2,
    name: "Shai Gilgeous-Alexander",
    team: "OKC",
    position: "G",
    stats: { pts: 31.1, reb: 4.3, ast: 6.6, stl: 1.4, blk: 0.8, to: 2.2 },
  },
  {
    id: 3,
    name: "Anthony Edwards",
    team: "MIN",
    position: "G",
    stats: { pts: 28.8, reb: 5.0, ast: 3.7, stl: 1.4, blk: 0.8, to: 2.9 },
  },
  {
    id: 4,
    name: "Jaylen Brown",
    team: "BOS",
    position: "G",
    stats: { pts: 28.7, reb: 6.9, ast: 5.1, stl: 1.0, blk: 0.4, to: 3.6 },
  },
  {
    id: 5,
    name: "Tyrese Maxey",
    team: "PHI",
    position: "G",
    stats: { pts: 28.3, reb: 4.1, ast: 6.6, stl: 1.9, blk: 0.8, to: 2.4 },
  },
  {
    id: 6,
    name: "Kawhi Leonard",
    team: "LAC",
    position: "F",
    stats: { pts: 27.9, reb: 6.4, ast: 3.6, stl: 1.9, blk: 0.4, to: 2.0 },
  },
  {
    id: 7,
    name: "Donovan Mitchell",
    team: "CLE",
    position: "G",
    stats: { pts: 27.9, reb: 4.5, ast: 5.7, stl: 1.5, blk: 0.3, to: 2.8 },
  },
  {
    id: 8,
    name: "Nikola Jokic",
    team: "DEN",
    position: "C",
    stats: { pts: 27.7, reb: 12.9, ast: 10.7, stl: 1.4, blk: 0.8, to: 3.7 },
  },
  {
    id: 9,
    name: "Devin Booker",
    team: "PHX",
    position: "G",
    stats: { pts: 26.1, reb: 3.9, ast: 6.0, stl: 0.8, blk: 0.3, to: 3.1 },
  },
  {
    id: 10,
    name: "Jalen Brunson",
    team: "NY",
    position: "G",
    stats: { pts: 26.0, reb: 3.3, ast: 6.8, stl: 0.8, blk: 0.1, to: 2.4 },
  },
  {
    id: 11,
    name: "Kevin Durant",
    team: "HOU",
    position: "F",
    stats: { pts: 26.0, reb: 5.5, ast: 4.8, stl: 0.8, blk: 0.9, to: 3.2 },
  },
  {
    id: 12,
    name: "Jamal Murray",
    team: "DEN",
    position: "G",
    stats: { pts: 25.4, reb: 4.4, ast: 7.1, stl: 0.9, blk: 0.4, to: 2.3 },
  },
  {
    id: 13,
    name: "Victor Wembanyama",
    team: "SA",
    position: "F",
    stats: { pts: 25.0, reb: 11.5, ast: 3.1, stl: 1.0, blk: 3.1, to: 2.4 },
  },
  {
    id: 14,
    name: "Deni Avdija",
    team: "POR",
    position: "F",
    stats: { pts: 24.2, reb: 6.9, ast: 6.7, stl: 0.8, blk: 0.6, to: 3.8 },
  },
  {
    id: 15,
    name: "Pascal Siakam",
    team: "IND",
    position: "F",
    stats: { pts: 24.0, reb: 6.6, ast: 3.8, stl: 1.1, blk: 0.4, to: 2.2 },
  },
  {
    id: 16,
    name: "Cade Cunningham",
    team: "DET",
    position: "G",
    stats: { pts: 23.9, reb: 5.5, ast: 9.9, stl: 1.4, blk: 0.8, to: 3.7 },
  },
  {
    id: 17,
    name: "James Harden",
    team: "LAC/CLE",
    position: "G",
    stats: { pts: 23.6, reb: 4.8, ast: 8.0, stl: 1.1, blk: 0.4, to: 3.5 },
  },
  {
    id: 18,
    name: "Jalen Johnson",
    team: "ATL",
    position: "F",
    stats: { pts: 22.5, reb: 10.3, ast: 7.9, stl: 1.2, blk: 0.4, to: 3.4 },
  },
  {
    id: 19,
    name: "Paolo Banchero",
    team: "ORL",
    position: "F",
    stats: { pts: 22.2, reb: 8.4, ast: 5.2, stl: 0.7, blk: 0.6, to: 3.1 },
  },
  {
    id: 20,
    name: "Norman Powell",
    team: "MIA",
    position: "G",
    stats: { pts: 21.7, reb: 3.5, ast: 2.5, stl: 1.1, blk: 0.2, to: 1.9 },
  },
  {
    id: 21,
    name: "Trey Murphy III",
    team: "NO",
    position: "F",
    stats: { pts: 21.5, reb: 5.7, ast: 3.8, stl: 1.5, blk: 0.4, to: 1.8 },
  },
  {
    id: 22,
    name: "Brandon Ingram",
    team: "TOR",
    position: "F",
    stats: { pts: 21.5, reb: 5.6, ast: 3.7, stl: 0.8, blk: 0.7, to: 2.4 },
  },
  {
    id: 23,
    name: "Julius Randle",
    team: "MIN",
    position: "F",
    stats: { pts: 21.1, reb: 6.7, ast: 5.0, stl: 1.1, blk: 0.2, to: 2.7 },
  },
  {
    id: 24,
    name: "Cooper Flagg",
    team: "DAL",
    position: "F",
    stats: { pts: 21.0, reb: 6.7, ast: 4.5, stl: 1.2, blk: 0.9, to: 2.3 },
  },
  {
    id: 25,
    name: "Zion Williamson",
    team: "NO",
    position: "F",
    stats: { pts: 21.0, reb: 5.7, ast: 3.2, stl: 1.0, blk: 0.5, to: 2.0 },
  },
  {
    id: 26,
    name: "LeBron James",
    team: "LAL",
    position: "F",
    stats: { pts: 20.9, reb: 6.1, ast: 7.2, stl: 1.2, blk: 0.6, to: 3.0 },
  },
  {
    id: 27,
    name: "Nickeil Alexander-Walker",
    team: "ATL",
    position: "G",
    stats: { pts: 20.8, reb: 3.4, ast: 3.7, stl: 1.3, blk: 0.5, to: 2.1 },
  },
  {
    id: 28,
    name: "Alperen Sengun",
    team: "HOU",
    position: "C",
    stats: { pts: 20.4, reb: 8.9, ast: 6.2, stl: 1.2, blk: 1.1, to: 3.2 },
  },
  {
    id: 29,
    name: "Brandon Miller",
    team: "CHA",
    position: "F",
    stats: { pts: 20.2, reb: 4.9, ast: 3.3, stl: 1.0, blk: 0.7, to: 2.5 },
  },
  {
    id: 30,
    name: "Bam Adebayo",
    team: "MIA",
    position: "C",
    stats: { pts: 20.1, reb: 10.0, ast: 3.2, stl: 1.2, blk: 0.7, to: 1.6 },
  },
  {
    id: 31,
    name: "Desmond Bane",
    team: "ORL",
    position: "G",
    stats: { pts: 20.1, reb: 4.1, ast: 4.1, stl: 1.0, blk: 0.5, to: 2.0 },
  },
  {
    id: 32,
    name: "LaMelo Ball",
    team: "CHA",
    position: "G",
    stats: { pts: 20.1, reb: 4.8, ast: 7.1, stl: 1.2, blk: 0.3, to: 2.8 },
  },
  {
    id: 33,
    name: "Karl-Anthony Towns",
    team: "NY",
    position: "C",
    stats: { pts: 20.1, reb: 11.9, ast: 3.0, stl: 0.9, blk: 0.5, to: 2.5 },
  },
  {
    id: 34,
    name: "Jalen Duren",
    team: "DET",
    position: "C",
    stats: { pts: 19.5, reb: 10.5, ast: 2.0, stl: 0.8, blk: 0.8, to: 1.9 },
  },
  {
    id: 35,
    name: "CJ McCollum",
    team: "ATL/WSH",
    position: "G",
    stats: { pts: 18.7, reb: 3.3, ast: 3.9, stl: 0.8, blk: 0.5, to: 1.8 },
  },
  {
    id: 36,
    name: "De'Aaron Fox",
    team: "SA",
    position: "G",
    stats: { pts: 18.6, reb: 3.8, ast: 6.2, stl: 1.2, blk: 0.3, to: 2.3 },
  },
  {
    id: 37,
    name: "Kon Knueppel",
    team: "CHA",
    position: "G",
    stats: { pts: 18.5, reb: 5.3, ast: 3.4, stl: 0.7, blk: 0.2, to: 2.0 },
  },
  {
    id: 38,
    name: "DeMar DeRozan",
    team: "SAC",
    position: "G",
    stats: { pts: 18.4, reb: 2.9, ast: 4.1, stl: 1.0, blk: 0.3, to: 1.2 },
  },
  {
    id: 39,
    name: "Amen Thompson",
    team: "HOU",
    position: "G",
    stats: { pts: 18.3, reb: 7.8, ast: 5.3, stl: 1.5, blk: 0.6, to: 2.4 },
  },
  {
    id: 40,
    name: "Evan Mobley",
    team: "CLE",
    position: "C",
    stats: { pts: 18.2, reb: 9.0, ast: 3.6, stl: 0.7, blk: 1.7, to: 1.9 },
  },
  {
    id: 41,
    name: "Scottie Barnes",
    team: "TOR",
    position: "F",
    stats: { pts: 18.1, reb: 7.5, ast: 5.9, stl: 1.4, blk: 1.5, to: 2.6 },
  },
  {
    id: 42,
    name: "Saddiq Bey",
    team: "NO",
    position: "G",
    stats: { pts: 17.7, reb: 5.6, ast: 2.5, stl: 0.9, blk: 0.1, to: 0.9 },
  },
  {
    id: 43,
    name: "Ryan Rollins",
    team: "MIL",
    position: "G",
    stats: { pts: 17.3, reb: 4.6, ast: 5.6, stl: 1.5, blk: 0.4, to: 2.7 },
  },
  {
    id: 44,
    name: "Chet Holmgren",
    team: "OKC",
    position: "C",
    stats: { pts: 17.1, reb: 8.9, ast: 1.7, stl: 0.6, blk: 1.9, to: 1.6 },
  },
  {
    id: 45,
    name: "Miles Bridges",
    team: "CHA",
    position: "F",
    stats: { pts: 17.1, reb: 5.8, ast: 3.2, stl: 0.6, blk: 0.4, to: 1.4 },
  },
  {
    id: 46,
    name: "Payton Pritchard",
    team: "BOS",
    position: "G",
    stats: { pts: 17.0, reb: 3.9, ast: 5.2, stl: 0.7, blk: 0.1, to: 1.4 },
  },
  {
    id: 47,
    name: "OG Anunoby",
    team: "NY",
    position: "F",
    stats: { pts: 16.7, reb: 5.2, ast: 2.2, stl: 1.6, blk: 0.7, to: 1.8 },
  },
  {
    id: 48,
    name: "Stephon Castle",
    team: "SA",
    position: "G",
    stats: { pts: 16.7, reb: 5.3, ast: 7.4, stl: 1.1, blk: 0.3, to: 3.2 },
  },
  {
    id: 49,
    name: "Derrick White",
    team: "BOS",
    position: "G",
    stats: { pts: 16.5, reb: 4.4, ast: 5.4, stl: 1.1, blk: 1.3, to: 1.7 },
  },
  {
    id: 50,
    name: "Immanuel Quickley",
    team: "TOR",
    position: "G",
    stats: { pts: 16.4, reb: 4.0, ast: 5.9, stl: 1.3, blk: 0.1, to: 1.5 },
  },
];
